functions:
  command-variant: beta
  name: my-cloud-function
  provider:
    project: my-google-project-name
    region: us-east1
  config:
    gen2: true
    entry-point: http-entry
    runtime: nodejs20
    trigger-http: true
    vpc-connector: project-vpc-connector
    min-instances: 1
    max-instances: 10
    concurrency: 800
    cpu: 1
    memory: 2GB
    quiet: true
    set-secrets:
      SECRET_VARIABLE: google-secret:version
